// AUTO-GENERATED by build-machines-data.mjs — do not edit by hand.
// Source: pixel art/conveyor/conveyor.png (Piskel export, 64x64 sheet)
// Delivered as base64 so the game runs from file:// without a server.
window.MACHINE_ASSETS = {
  conveyor: {
    // The Piskel atlas JSON names the image "New Piskel.png", which does not
    // match the actual file — so we skip Pixi's spritesheet parser and build
    // frame textures directly from this embedded PNG (see index.html).
    image: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAACeklEQVR4AexaAW6DMAzM9ptK/Xm/U4nnbBwtUdthn8IlxJmYago4d7aPUzaJfSf/52dO14iZZtenRm1wmMU9AVygybid2MO1B7NdPSWTyxMgXa/XKmF1xe4fUd8SwFSMNe3kSzhL1jol31KbnJYAGXm5XJISmSjoCRVgmqakRNC5c1tUgLyy04niPmBZ2+EFUNwH7PACsAHUPHUAbKSE2mBrPBUANlKi9QAqPxVALaDiFfcBy+qHF0BxH7DDC8AGUPPUAbCREmqDrfFUANhIidYDlPJ/rqcCfAKOvlbcByzrN7wAivuAHV4ANoCapw6AjZRQG2yNpwLARkq0HkDlpwKoBVS84j5gWf3wAijuA3Z4AdgAap46ADZSQm2wNZ4KABsp0XoAlZ8KoBZQ8Yr7gGX1wwuguA/Y4QVgA6h5ywFfKzFspMTKM39nzvmcfUrWMq41v8lpCbCA7vd7ut1uUoBjIdtxALZGeKU9ATYV88ic3B6uPZg/LTxvmFyeAE9s1y80XiPMITwBNt+mmkx+oiaXX6kw6wlQ5X8D8I6/sKdDl1sC5Cem/AYA9mWazPlyr/upJUBuDH9MKJGJgp5QAYL2Xa2tU4BqUg5KRB2AjUyJ6LpQAZQNENjhBYg+gNofdYBaIDr+FIA9IWUDBJbx985TB2AjU6L3gKw+FYARRMuX9nMKUKrYf1tPHYCNTInoglEBlA0Q2OEFiD6A2h91gFogOv4UgD0hZQMElvH3zlMHYCNToveArD4VgBGMnj8FGP0Jqv1TB2AjU0JtsDXeEgAvJJfaygYI7ELyOGTOx2WMoyXA0l2Nd/PgWMiCHjwBaj6xmlxvUqoXvwAAAP//Gi3VVQAAAAZJREFUAwASQ9KcdBm/EQAAAABJRU5ErkJggg==",
    frames: [{"x":0,"y":0},{"x":32,"y":0},{"x":0,"y":32}],
    frameWidth: 32,
    frameHeight: 32,
    trim: {"x":5,"y":0,"w":22,"h":32},          // real content bounds inside each frame
    stripePeriod: 5,          // px between slats
    frameShift: 2,              // px slats travel per frame (downward)
    // Future: a seamless cap-less strip tile here switches belt runs to
    // TilingSprites (one per row, animated via tilePosition) automatically.
    tile: null
  }
};
